QASite.Web/Models/ErrorViewModel.cs
namespace QASite.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

QASite.Web/Models/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace QASite.Web.Models
{
    public class LoginViewModel
    {
        public string ReturnUrl { get; set; }
    }
}

QASite.Web/Models/ViewQuestionViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using QASite.Data;

namespace QASite.Web.Models
{
    public class ViewQuestionViewModel
    {
        public Question Question { get; set; }
        public User CurrentUser { get; set; }
    }
}

QASite.Web/Controllers/AccountController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.Extensions.Configuration;
using QASite.Data;
using QASite.Web.Models;

namespace QASite.Web.Controllers
{
    public class AccountController : Controller
    {
        private readonly string _connectionString;

        public AccountController(IConfiguration configuration)
        {
            _connectionString = configuration.GetConnectionString("ConStr");
        }

        public IActionResult Login(string returnUrl)
        {
            return View(new LoginViewModel { ReturnUrl = returnUrl });
        }

        [HttpPost]
        public IActionResult Login(string email, string password, string returnUrl)
        {
            var db = new UserRepository(_connectionString);
            var user = db.Login(email, password);
            if (user == null)
            {
                return RedirectToAction("Login");
            }

            var claims = new List<Claim>
            {
                new Claim("user", email)
            };
            HttpContext.SignInAsync(new ClaimsPrincipal(
                new ClaimsIdentity(claims, "Cookies", "user", "role"))).Wait();
            if (!String.IsNullOrEmpty(returnUrl))
            {
                return Redirect(returnUrl);
            }
            return Redirect("/home");
        }

        public IActionResult Signup()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Signup(User user, string password)
        {
            var db = new UserRepository(_connectionString);
            db.AddUser(user, password);
            return RedirectToAction("Index", "Home");
        }

        public IActionResult Logout()
        {
            HttpContext.SignOutAsync().Wait();
            return Redirect("/");
        }
    }
}

QASite.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using QASite.Data;
using QASite.Web.Models;
using System.Diagnostics;

namespace QASite.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly string _connectionString;

        public HomeController(IConfiguration configuration)
        {
            _connectionString = configuration.GetConnectionString("ConStr");
        }

        public IActionResult Index()
        {
            var repo = new QuestionsRepository(_connectionString);
            return View(repo.Get());
        }
    }
}

QASite.Web/Controllers/QuestionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using QASite.Data;
using QASite.Web.Models;

namespace QASite.Web.Controllers
{
    public class QuestionsController : Controller
    {
        private readonly string _connectionString;

        public QuestionsController(IConfiguration configuration)
        {
            _connectionString = configuration.GetConnectionString("ConStr");
        }

        [Authorize]
        public IActionResult AskAQuestion()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public IActionResult Add(Question question, List<string> tags)
        {
            question.Date = DateTime.Now;
            var userRepo = new UserRepository(_connectionString);
            var user = userRepo.GetByEmail(User.Identity.Name);
            question.UserId = user.Id;
            var questionsRepo = new QuestionsRepository(_connectionString);
            questionsRepo.AddQuestion(question, tags);
            return RedirectToAction("ViewQuestion", new { id = question.Id });
        }

        public IActionResult ViewQuestion(int id)
        {
            var questionsRepo = new QuestionsRepository(_connectionString);
            var question = questionsRepo.Get(id);
            var viewModel = new ViewQuestionViewModel
            {
                Question = question
            };
            if (User.Identity.IsAuthenticated)
            {
                var userRepo = new UserRepository(_connectionString);
                viewModel.CurrentUser = userRepo.GetByEmail(User.Identity.Name);
            }
            if (question == null)
            {
                return Redirect("/");
            }

            return View(viewModel);
        }

        [HttpPost]
        [Authorize]
        public IActionResult AddAnswer(int questionId, string text)
        {
            var userRepo = new UserRepository(_connectionString);
            var user = userRepo.GetByEmail(User.Identity.Name);
            var answer = new Answer
            {
                Date = DateTime.Now,
                Text = text,
                QuestionId = questionId,
                UserId = user.Id
            };
            var questionRepo = new QuestionsRepository(_connectionString);
            questionRepo.AddAnswer(answer);
            return RedirectToAction("ViewQuestion", new { id = questionId });
        }

        [HttpPost]
        [Authorize]
        public void AddQuestionLike(int questionId)
        {
            var userRepo = new UserRepository(_connectionString);
            var user = userRepo.GetByEmail(User.Identity.Name);
            var questionRepo = new QuestionsRepository(_connectionString);
            questionRepo.AddQuestionLike(questionId, user.Id);
        }

        public IActionResult GetLikes(int questionId)
        {
            var questionRepo = new QuestionsRepository(_connectionString);
            return Json(new { likes = questionRepo.GetQuestionLikes(questionId) });
        }
    }
}

QASite.Web/Views/Home/Index.cshtml
@model List<QASite.Data.Question>

<div class="row">
    <div class="col-md-8 offset-md-2" style="margin-top:100px">
        @foreach (var question in Model)
        {
            <div class="card card-body bg-light">
                <h4>
                    <a href="/questions/viewquestion?id=@question.Id">
                        @question.Title
                    </a>
                </h4>
                <div>
                    <span>Tags:</span>
                    @foreach (var qt in question.QuestionsTags)
                    {
                        <span class="badge badge-primary">@qt.Tag.Name</span>
                    }
                </div>
                <div style="margin-top: 10px;">
                    @(question.Text.Length < 200 ? question.Text : (question.Text.Substring(0, 200) + "..."))
                </div>
                <span>Likes: @question.Likes.Count</span>
                <br />
                <span>@question.Answers.Count answer(s)</span>
            </div>
        }
    </div>
</div>

QASite.Web/Views/Questions/AskAQuestion.cshtml
<div class="row" style="min-height: 80vh; display:flex; align-items: center;">
    <div class="col-md-8 offset-md-2 bg-light p-4 rounded shadow">
        <h2>Ask a question</h2>
        <form method="post" action="/questions/add">
            <input class="form-control" name="title" placeholder="Title"/>
            <br/>
            <textarea class="form-control" placeholder="Type your question here..." rows="10" name="text"></textarea>
            <br/>
            <select multiple class="form-control" id="tags" name="tags"></select>
            <br/>
            <button class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>
@section scripts {
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-tagsinput/0.8.0/bootstrap-tagsinput.js"></script>
    <script>
        $(() => {
            $("#tags").tagsinput({
                tagClass: 'badge bg-primary'
            });
        })
    </script>
}

@section styles
{
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-tagsinput/0.8.0/bootstrap-tagsinput.css" />
}

QASite.Web/Views/Questions/ViewQuestion.cshtml
@model ViewQuestionViewModel

<div class="row" style="margin-top:100px;">
    <div class="col-md-10 offset-md-2 bg-light p-4 rounded shadow">
        <h2>@Model.Question.Title</h2>
        <hr />
        @foreach (var paragraph in Model.Question.Text.Split("\r\n"))
        {
            <p>@paragraph</p>
        }
        <hr />
        <span>Asked by @Model.Question.User.Name</span>
        on
        <span>@Model.Question.Date.ToLongDateString()</span>
        <br />
        <span>Tags:</span>
        @foreach (var qt in Model.Question.QuestionsTags)
        {
            <span class="badge bg-primary">@qt.Tag.Name</span>
        }
        <br />
        <span>Likes: </span> <span data-question-id="@Model.Question.Id" id="likes-count">@Model.Question.Likes.Count</span>
        <br />
        @if (Model.CurrentUser != null)
        {
            if (Model.Question.Likes.Any(l => l.UserId == Model.CurrentUser.Id))
            {
                <i style="font-size: 40px; cursor: pointer;" class="bi bi-heart-fill text-danger"></i>
            }
            else
            {
                <i style="font-size: 40px; cursor: pointer;" class="bi bi-heart-fill" id="like-question" data-question-id="@Model.Question.Id"></i>
            }
        }
    </div>
</div>
<div class="row">
    <div class="col-md-8 offset-md-2 mt-4">
        <h3>Answers:</h3>
    </div>
</div>

@if (Model.Question.Answers.Count == 0)
{

    <div class="row">
        <div class="col-md-8 offset-md-2 card card-body bg-light">
            <h3>No answers yet, be the first to submit one!</h3>
        </div>
    </div>
}
else
{
    foreach (var answer in Model.Question.Answers)
    {

        <div class="row">
            <div class="col-md-8 offset-md-2 card card-body bg-light">
                <div>@answer.Text</div>
                <br />
                <span>Answered by @answer.User.Name</span>
                <span>on</span>
                <span>@answer.Date.ToLongDateString()</span>
                <hr />
            </div>
        </div>
    }
}


@if (Model.CurrentUser != null)
{
    <div class="row">
        <div class="col-md-8 offset-md-2 card card-body bg-light mt-4">
            <h2>Submit an answer</h2>
            <form method="post" action="/questions/addanswer">
                <input type="hidden" name="questionid" value="@Model.Question.Id" />
                <textarea class="form-control" placeholder="Type your answer here..." rows="10" name="text"></textarea>
                <br />
                <button class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
}

@section scripts
{
    <script src="/js/view-question.js"></script>
}

@section styles 
{
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
}

QASite.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - QASite.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/QASite.Web.styles.css" asp-append-version="true" />
    @await RenderSectionAsync("styles", false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-dark fixed-top bg-dark border-bottom box-shadow">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">QASite</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li><a class="nav-link text-light" asp-controller="Questions" asp-action="AskAQuestion">Ask a Question</a></li>
                        @if (!User.Identity.IsAuthenticated)
                        {
                            <li><a class="nav-link text-light" asp-controller="Account" asp-action="Login">Login</a></li>
                        }
                        else
                        {
                            <li><a class="nav-link text-light" asp-controller="Account" asp-action="Logout">Logout</a></li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>